Add write_to_socket function and support loading of hive tables in read_from_socket function
SneaksAndData/spark-utils pull request #88
Opened 2023-01-17 14:55 UTC by JanusAsmussen

2023-01-18 09:59 UTC, george-zubrienko requested changes
Some comments

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    partition_count = partition_count or 200
```suggestion
```

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    partition_count: int = None,
```suggestion
    partition_count: Optional[int] = 100,
```

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    partition_by: List[str] = None,
```suggestion
    partition_by: Optional[List[str]] = None,
```

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    :param partition_count: Number of partitions to use
```suggestion
    :param partition_count: Number of partitions to split result into.
```

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +        .options(**kwargs)
```suggestion
    prepared = data.repartition(partition_count, *partition_by) if partition_count else data
    
    prepared
        .write \
        .mode('overwrite') \
        .options(**write_options)
```

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    **kwargs
```suggestion
    write_options: Dict[str, str]
```
Using **kwargs in public APIs is a no-go :)

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    :param partition_count: Number of partitions to use
and please add docstring for write_options, including links to spark docs for examples (csv, parquet, json maybe)

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +            .format('delta') \
```suggestion
            .format(socket.data_format) \
```

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    elif socket.data_format in ['hive']:
```suggestion
    elif socket.data_format in ['hive_delta']:
```
We can also have parquet/other tables in hive

2023-01-18 09:59 UTC, george-zubrienko commented on spark_utils/common/functions.py
> +    if socket.data_format == 'hive':
```suggestion
    if socket.data_format.startswith('hive'):
```

2023-01-19 11:31 UTC, JanusAsmussen commented
create_package

2023-01-19 11:41 UTC, JanusAsmussen commented
create_package

2023-01-19 11:50 UTC, JanusAsmussen commented
create_package

2023-01-19 16:17 UTC, JanusAsmussen commented
create_package

2023-01-20 09:48 UTC, JanusAsmussen commented
create_package

2023-01-23 11:56 UTC, JanusAsmussen commented
create_package

2023-01-23 13:47 UTC, george-zubrienko approved these changes

2023-01-23 14:01 UTC, merged